// Generates src/version.ts from package.json — the single source of truth for the CLI
// version string. Run by the release pipeline (.releaserc `@semantic-release/exec`
// prepareCmd) right after the version bump, and the result is committed, so
// `mockstar version` (and the init `$schema` minor tag) never go stale.
//
// Not type-checked/linted (scripts/ is outside the tsc + biome globs, like
// generate-schema.ts); the emitted src/version.ts IS checked.
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import pkg from "../package.json";

const out = resolve(import.meta.dir, "..", "src", "version.ts");
const body = `// GENERATED by scripts/sync-version.ts from package.json — do not edit by hand.\nexport const MOCKSTAR_VERSION = ${JSON.stringify(pkg.version)};\n`;
await writeFile(out, body);
process.stdout.write(`wrote src/version.ts (${pkg.version})\n`);
